Add short option parsing to ds environment script.

diff --git a/ds-env-setup b/ds-env-setup
--- a/ds-env-setup
+++ b/ds-env-setup
@@ -1,10 +1,38 @@
 #!/bin/bash
 set -e
 
+usage() {
+    echo ""
+    echo -e "Usage: $0 name [opts]"
+    echo -e "\t-h for help message and options."
+    echo ""
+}
+
+# Option parsing
+while getopts ":hp:" opt; do
+    case $opt in
+        h)
+            # Help command
+            usage
+            exit 0
+            ;;
+        p)
+            # Python version
+            PY_ENV=$OPTARG
+            ;;
+        \?)
+            # Invalid option
+            echo ""
+            echo "ERROR: Invalid option."
+            usage
+            exit 1
+            ;;
+    esac
+done
+shift $((OPTIND -1))
+
 ENV_NAME=$1
 CONDA_BASE=$(conda info --base)
-
-echo "ENV_NAME=$ENV_NAME"
 
 # If an environment exists under the given name, then skip the creation process.
 # I chose to do this so that this script could be extended without having to
